# Generated by Django 4.2.3 on 2023-09-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='ls_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ls_admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='ls_superadmin',
            new_name='is_superadmin',
        ),
    ]
